apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web-label
  template:
    metadata:
      labels:
        app: nginx-web-label
    spec:
      containers:
        - name: nginx-container
          image: haegihaegi/nginx:377d77033527ea9db2a6a52eafd07107aae6b977
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-web-label
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP